"""created total_expenses table

Revision ID: 951393e60649
Revises: 00240ec1ad2a
Create Date: 2024-09-19 10:48:48.767417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951393e60649'
down_revision = '00240ec1ad2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_budgeted', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('total_expenses')
    # ### end Alembic commands ###
