"""create save_goals table

Revision ID: 00240ec1ad2a
Revises: 6c349db83c8a
Create Date: 2024-09-19 10:21:40.669436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00240ec1ad2a'
down_revision = '6c349db83c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save_goals')
    # ### end Alembic commands ###
